theme: jekyll-theme-cayman
title: Tutorial on XXL Language Models for Data Scientists
description: Material for my VLDB'22 and BTW'23 tutorials on language models and their applications in data management
